# Generated by Django 5.2.11 on 2026-03-05 07:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_alter_result_options_alter_teachercourse_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='student_in_courses', through='learning.UserCourse', through_fields=('course', 'user'), to=settings.AUTH_USER_MODEL, verbose_name='Ученики'),
        ),
    ]
