# Generated by Django 5.2.11 on 2026-03-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_course_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='courses/covers/', verbose_name='Обложка курса'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='lessons/files/', verbose_name='Прикрепленный файл'),
        ),
    ]
